### ISSUE TITLE
既然开源出来了，为什么要混淆？

### ISSUE THREAD

**Issue by Jeyrce** [soul-F/dmdb_exporter#2]
文件从a开始一直命名到z？文件中声明了一堆结构体名字全是神秘代号？函数执行了一堆逻辑，最后返回一个固定数字8？既然开源出来了还混淆干嘛？

**Comment by soul-F** [comment]
注释都不会看。dm下的文件，是达梦提供的驱动包。为什么a-z，为什么混淆，请去问达梦。
